#!/bin/sh
project=$1

if ! tmux has-session -t "$project" 2> /dev/null; then
  cd "$HOME/dev/$project"
  tmux new-session -d -s "$project" -n 'editor'

  tmux send-keys 'vim' C-m
  tmux split-window -v -p 30
  tmux split-window -h

  tmux new-window -t "$project":2 -n 'servers'
  tmux split-window -h
  tmux send-keys 'zeus start' C-m
  tmux split-window -v
  tmux send-keys 'zeus s' C-m
  tmux select-pane -t 1
   
  tmux select-window -t 1
  tmux select-pane -t 3
  tmux send-keys 'zeus c' C-m
  tmux select-pane -t 1
  tmux send-keys ':Gstatus' C-m 
fi
tmux attach-session -t "$project"
